### ISSUE TITLE
Swapping voices

### ISSUE THREAD

**Issue by ProphecyCoffee** [Sebane1/FFXIVVoicePackCreator#2]
hi I'm new to well this level of modding. Is there a way to swap voices using this program? I was a bit lost when it asked me if I have voice dumps through ffxivexplorer. How would i make one using that tool? I wanted to replace hyur male voice 1 with Viera veena's voice 2. I know how to make the folder and what's not in penumbra mod folder. But how do I pull the voice file for the swap from sqpack?

**Comment by Sebane1** [comment]
So, actually tracking down voice files can be a bit of its own process.

FFXIVExplorer is a common way of being able to pull all sorts of assets and sounds out of the game. However, not all files end up with correct file names. 
http://ffxivexplorer.fragmenterworks.com/about.php

There's about 1400+ individual voice sounds that don't have a name that lines up with the file paths FFXIV recognizes.

Because of this, this tool is currently unable to really receive a feature where it can automate voice swapping.  

When the program is given a voice dump folder to look at, it attempts to sort through all the .wav files for easier access and listening, but you'll still have to listen and track down which files might be the voice you're looking for if the file didn't have a valid name.

Once you actually have the files found however, you should be able to take the exported voice files from FFXIVExplorer, assign them to each emote using this tool, and then export to a folder.

**Comment by ProphecyCoffee** [comment]
Thank you so much!

**Comment by Sebane1** [comment]
Was just reading through git issues, making an addendum here to say that this tool supports voice swaps now.
